Zenia-Graph-Sf/force-app/main/default/objects/Lead/fields/Datasource__c.field-meta.xml
<CustomField>
    <fullName>Datasource__c</fullName>
    <label>Datasource</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crunch Base</fullName>
            </value>
            <value>
                <fullName>linkedin</fullName>
                <label>LinkedIn</label>
            </value>
            <value>
                <fullName>salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>dbpedia</fullName>
                <label>DBPedia</label>
            </value>
            <value>
                <fullName>zoominfo</fullName>
                <label>ZoomInfo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Zenia-Graph-Sf/force-app/main/default/objects/Lead/fields/Niacs_Code__c.field-meta.xml
<CustomField>
    <fullName>Niacs_Code__c</fullName>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Zenia-Graph-Sf/force-app/main/default/objects/Lead/fields/SICCode__c.field-meta.xml
<CustomField>
    <fullName>SICCode__c</fullName>
    <label>SIC Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Zenia-Graph-Sf/force-app/main/default/classes/zeniaExtendListViewsTest.cls
@isTest
public class zeniaExtendListViewsTest {
   
    static testMethod void testzeniaExtendListViews() 
    {
        List<Lead> lstLead = new List<Lead>();
         
       Lead leadObj = new Lead();
        leadObj.Company= 'Apple';
        leadObj.industry= 'Banking';
        leadObj.Status = 'Active' ;
        leadObj.Datasource__c = 'Linkedin';
        leadObj.SICCode__c = '8765';
        leadObj.Niacs_Code__c = '876543';
        leadObj.LastName = 'Ab';
        lstLead.add(leadObj);
        insert lstLead; 
       
        Test.startTest();
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstLead);
        zeniaExtendListViews ext = new zeniaExtendListViews(stdSetController);
        Test.stopTest();
    }
}