Zenia-Graph-Sf/force-app/main/default/objects/Lead/fields/Datasource__c.field-meta.xml
<CustomField>
    <fullName>Datasource__c</fullName>
    <label>Datasource</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crunch Base</fullName>
            </value>
            <value>
                <fullName>linkedin</fullName>
                <label>LinkedIn</label>
            </value>
            <value>
                <fullName>salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>dbpedia</fullName>
                <label>DBPedia</label>
            </value>
            <value>
                <fullName>zoominfo</fullName>
                <label>ZoomInfo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Zenia-Graph-Sf/force-app/main/default/objects/Lead/fields/Niacs_Code__c.field-meta.xml
<CustomField>
    <fullName>Niacs_Code__c</fullName>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Zenia-Graph-Sf/force-app/main/default/objects/Lead/fields/SICCode__c.field-meta.xml
<CustomField>
    <fullName>SICCode__c</fullName>
    <label>SIC Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Zenia-Graph-Sf/force-app/main/default/classes/ZeniaRestApiLead.cls
@RestResource(urlMapping='/lead/*')
global class ZeniaRestApiLead {
     @HttpPost
    global static map<String,String> createLead( String company,String industry, String status, String datasource, String lastName, String sicCode, String niacCode ){
           Id ldids;
           
            Lead lds = new Lead();
            lds.Company= company;
            lds.industry= industry;
            lds.Status = status; 
            lds.Datasource__c = datasource;
            lds.SICCode__c =sicCode;
            lds.Niacs_Code__c =niacCode;
            lds.LastName = lastName;
            insert lds;
            ldids = lds.Id;
            system.debug('ID IS = '+ ldids);
        Map<String,String> mapRes = new Map<string,String>();
        mapres.put('id',ldids);
        mapres.put('status','Success');
        return mapRes;
        	
    }   
    }